stages:
  - test

variables:
  PYTHON_VERSION: "3.8"

before_script:
  - apt-get update -qy
  - apt-get install -y python3 python3-pip
  - python3 -V
  - pip3 install -r requirements.txt

test:
  stage: test
  script:
    - python3 -m pytest
  only:
    - main
    - dev